-- P1-9: 알림톡 통합을 위한 새 NotificationType 값 추가

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ENROLLMENT_COMPLETE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_COMPLETE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REFUND_COMPLETE';
