project_id = "class-pass"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "class_pass"]
extra_search_path = ["public", "extensions", "class_pass"]
max_rows = 1000

[db]
port = 54322
