export const CONFIGURATION_LABELS: Record<string, string> = {
  settings:"운영 설정", periods:"시간표", pointRules:"상벌점 규칙", rooms:"강의실", seats:"좌석", tuitionPlans:"수강료", paymentCategories:"수납 항목", examTypes:"시험 종류", examSchedules:"시험 일정",
  name:"이름", label:"표시 이름", displayOrder:"표시 순서", startTime:"시작 시각", endTime:"종료 시각", isMandatory:"필수 교시", isActive:"사용", category:"분류", points:"점수", description:"설명", columns:"가로 좌석 수", rows:"세로 좌석 수", aisleColumns:"통로 위치", studyRoomId:"강의실", positionX:"가로 위치 (1부터)", positionY:"세로 위치 (1부터)", amount:"금액", durationDays:"기간 (일)", studyTrack:"대상 직렬", subjects:"과목", totalItems:"문항 수", pointsPerItem:"문항 배점", alternateGroup:"선택 과목 그룹", type:"시험 구분", examDate:"시험일",
  warnLevel1:"1차 경고 기준", warnLevel2:"2차 경고 기준", warnInterview:"면담 기준", warnWithdraw:"퇴실 기준", warnMsgLevel1:"1차 경고 문구", warnMsgLevel2:"2차 경고 문구", warnMsgInterview:"면담 문구", warnMsgWithdraw:"퇴실 문구",
  halfDayPeriodCount:"반휴 적용 교시 수", tardyMinutes:"지각 기준 (분)", assistantPastEditAllowed:"조교 과거 출결 수정 허용", assistantPastEditDays:"조교 수정 허용 일수", holidayLimit:"월 휴무권", halfDayLimit:"월 반휴권", healthLimit:"월 병가 한도", holidayUnusedPts:"미사용 휴무권 상점", halfDayUnusedPts:"미사용 반휴권 상점", tardyPointRuleId:"지각 벌점 규칙", absentPointRuleId:"결석 벌점 규칙",
  perfectAttendancePtsEnabled:"일일 개근 상점 사용", perfectAttendancePts:"일 개근 상점", perfectAttendanceWeeklyPts:"주 개근 상점", perfectAttendanceMonthlyPts:"월 개근 상점", expirationWarningDays:"수강 만료 사전 안내 (일)", operatingDays:"운영 요일", studyTracks:"직렬", pointCategories:"상벌점 분류", featureFlags:"사용 기능", managementPolicy:"별도 관리규정", examPointAutomation:"시험·휴무 자동 정산", examAnalysis:"성적 분석 기준",
  attendanceManagement:"출석 관리", announcements:"공지", phoneSubmissions:"휴대폰 관리", studentManagement:"학생 관리", seatManagement:"좌석 관리", pointManagement:"상벌점 관리", leaveManagement:"휴무 관리", warningManagement:"경고 관리", interviewManagement:"면담", examManagement:"성적 관리", examScheduleManagement:"시험 일정", paymentManagement:"수납", reporting:"통계", staffManagement:"직원", staffChat:"직원 채팅",
  mon:"월", tue:"화", wed:"수", thu:"목", fri:"금", sat:"토", sun:"일", enabled:"사용", effectiveFrom:"시작일", version:"규정 이름", attendancePeriodIds:"출결 대상 교시", controlledPeriods:"요일별 관리 교시", periodId:"교시", weekdays:"적용 요일", optional:"선택 신청 교시", syncAttendance:"성적 등록 시 자동 출석", morningExam:"아침모의고사 교시", closingTime:"운영 종료 시각", breaks:"휴식 시간", monthlyPoints:"상벌점 월별 집계", separateMeritDemerit:"상점·벌점 분리 집계", managerConfirmsAttendance:"출결 벌점 관리자 확정",
  fullDayAbsenceRuleId:"종일 결석 규칙", partialAbsenceRuleId:"교시 결석 규칙", tardyRuleId:"지각 규칙", lateArrivalPolicy:"지각 기준 방식", phone:"휴대폰 규정", shortLoanMinutes:"기본 반출 시간 (분)", resubmitBeforeMinutes:"교시 시작 전 반납 안내 (분)", repeatDays:"반복 반출 집계 (일)", repeatCount:"반복 반출 검토 횟수", allowBulkRental:"일괄 반출 허용", loanPlace:"기본 반출 장소",
  earlyExit:"조기 퇴실", ruleId:"벌점 규칙", windowDays:"집계 기간 (일)", interviewCount:"면담 검토 횟수", missionCount:"개선 과제 검토 횟수", missionDays:"개선 과제 기간 (일)", unauthorizedEntry:"무단 출입", monthlyReviewCount:"월 검토 횟수", patrolsPerPeriod:"교시별 순찰 안내 횟수", dailyGoalCount:"일일 목표 안내 수", appealDays:"이의 신청 안내 기한 (일)", holidayPriorNotice:"휴무 사전 신청", healthExemptFromLimit:"증빙 병가 한도·휴무권 차감 면제", warningLabels:"경고 단계 이름", WARNING_1:"1차 경고", WARNING_2:"2차 경고", INTERVIEW:"면담", WITHDRAWAL:"퇴실", guidance:"학생 안내 규정", title:"제목", text:"내용",
  morningStartDate:"아침시험 시작일", morningWeekdays:"아침시험 요일", morningExcludedDates:"아침시험 휴강일", rankAggregation:"월 성적 집계", rankTieBreak:"동점 처리", morningAbsenceRuleId:"아침시험 미응시 벌점", regularAbsenceRuleId:"정기시험 미응시 벌점", morningFirstRuleId:"아침시험 월 1등 상점", regularFirstRuleId:"정기시험 월 1등 상점", regularSecondRuleId:"정기시험 월 2등 상점", regularThirdRuleId:"정기시험 월 3등 상점", morningMonthlyRuleId:"아침시험 월 개근 상점", settleUnusedLeaveAutomatically:"미사용 휴무권 월 자동 정산",
  totalDropPercent:"총점 하락 (%)", rankDropPercent:"석차 하락 (%)", targetGapPercent:"목표 격차 (%)", weakSubjectRatePercent:"취약 과목 득점률 (%)", balanceStdDev:"과목 균형 기준", easyMissedRatePercent:"우선 복습 정답률 (%)", killerRatePercent:"고난도 정답률 (%)",
  morning:"아침시험 분석", regular:"정기시험 분석", common:"공통 분석", consecutiveDrops:"연속 하락 횟수", classGapPercent:"반 평균 격차 (%)", ownAverageDropPercent:"본인 평균 하락 (%)", movingAverageSessions:"이동평균 응시 횟수", trendWindowSessions:"추세 응시 횟수", attendanceRatePercent:"추세 판단 최소 응시율 (%)", easyItemCorrectRate:"쉬운 문항 정답률", highDiscriminationThreshold:"문항 변별도 기준",
};
export const CONFIGURATION_GROUPS = ["settings","periods","pointRules","rooms","seats","tuitionPlans","paymentCategories","examTypes","examSchedules"] as const;
export const CONFIGURATION_ENUMS: Record<string, [string,string][]> = {
  lateArrivalPolicy:[["threshold","설정한 분부터 지각"],["after_start","시작 시각 이후 지각"]],
  rankAggregation:[["AVERAGE","월평균"],["TOTAL","월 누적"]],
  rankTieBreak:[["SHARED","공동 순위"],["ATTEMPTS_STUDY_TIME","응시 횟수·학습 시간"]],
  type:[["WRITTEN","필기"],["PHYSICAL","체력"],["INTERVIEW","면접"],["RESULT","발표"],["OTHER","기타"]],
};
