DO $$
BEGIN
  CREATE TYPE "AcademyType" AS ENUM ('POLICE', 'FIRE', 'CIVIL_SERVICE', 'OTHER');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS "academies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "type" "AcademyType" NOT NULL DEFAULT 'POLICE',
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "academies_code_key" ON "academies"("code");

INSERT INTO "academies" ("id", "code", "name", "type", "isActive", "createdAt", "updatedAt")
VALUES (1, 'police-main', '한국경찰학원', 'POLICE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

DO $$
DECLARE
  academy_seq TEXT;
BEGIN
  academy_seq := pg_get_serial_sequence('"academies"', 'id');
  IF academy_seq IS NOT NULL THEN
    EXECUTE format(
      'SELECT setval(%L, %s, true)',
      academy_seq,
      COALESCE((SELECT MAX("id") FROM "academies"), 1)
    );
  END IF;
END
$$;

ALTER TABLE "academy_settings"
  ADD COLUMN IF NOT EXISTS "academyId" INTEGER;

UPDATE "academy_settings"
SET "academyId" = 1
WHERE "academyId" IS NULL;

ALTER TABLE "academy_settings"
  ALTER COLUMN "academyId" SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "academy_settings_academyId_key"
  ON "academy_settings"("academyId");

CREATE SEQUENCE IF NOT EXISTS "academy_settings_id_seq";
ALTER TABLE "academy_settings"
  ALTER COLUMN "id" SET DEFAULT nextval('"academy_settings_id_seq"');
ALTER SEQUENCE "academy_settings_id_seq"
  OWNED BY "academy_settings"."id";
SELECT setval('"academy_settings_id_seq"', COALESCE((SELECT MAX("id") FROM "academy_settings"), 1), true);

DO $$
BEGIN
  ALTER TABLE "academy_settings"
    ADD CONSTRAINT "academy_settings_academyId_fkey"
    FOREIGN KEY ("academyId") REFERENCES "academies"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TABLE "admin_users"
  ADD COLUMN IF NOT EXISTS "academyId" INTEGER;

UPDATE "admin_users"
SET "academyId" = CASE
  WHEN "role" = 'SUPER_ADMIN' THEN NULL
  ELSE COALESCE("academyId", 1)
END;

CREATE INDEX IF NOT EXISTS "admin_users_academyId_role_idx"
  ON "admin_users"("academyId", "role");

DO $$
BEGIN
  ALTER TABLE "admin_users"
    ADD CONSTRAINT "admin_users_academyId_fkey"
    FOREIGN KEY ("academyId") REFERENCES "academies"("id")
    ON DELETE SET NULL
    ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;